{% set name = "einops" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6f6c78739316a2e3ccbce8052310497e69da092935e4173f2e76ec4e3a336a35

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling >=1.10.0
  run:
    - python >=3.7

test:
  imports:
    - einops
    - einops.layers

about:
  home: https://github.com/arogozhnikov/einops
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A new flavour of deep learning operations.
  description: |
    Flexible and powerful tensor operations for readable and reliable code.
    Supports numpy, pytorch, tensorflow, and others.
  doc_url: https://github.com/arogozhnikov/einops
  dev_url: https://github.com/arogozhnikov/einops

extra:
  recipe-maintainers:
    - asford
