{% set name = "einops" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: de5d960a7a761225532e0f1959e5315ebeafc0cd43394732f103ca44b9837e84

build:
  skip: true # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - hatchling >=1.10.0
  run:
    - python

test:
  imports:
    - einops
    - einops.layers
  commands:
    - pip check
    - python -m einops.tests.run_tests numpy
  requires:
    - pip
    - pytest
    - numpy

about:
  home: https://einops.rocks/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Flexible and powerful tensor operations for readable and reliable code.
  description: |
    Flexible and powerful tensor operations for readable and reliable code.
    Supports numpy, pytorch, tensorflow, and others.
  doc_url: https://einops.rocks/
  dev_url: https://github.com/arogozhnikov/einops

extra:
  recipe-maintainers:
    - maresb
    - asford
