travis:
  secure:
    BINSTAR_TOKEN: mgpUCSsN5KjZhULMPUd02yhgQuoqB5GDM5mpy3Cf9SG33pfs5wl7zN9zb2TpImT2Lu2gcDtPQIUO2v7o+xUcd5t+ey42K8yqS1ELSt9rFhfWaidL/t9WI7pGnxLxtlhSV8xB73FayTouk4WLzd6Xj3P5OwwuA9UxXDmj4CoGdnxagjbo4vnqmsafEI//nUWrQXfaTQuMRd/LQ5cB7d0Y15Au0liW2dfHMp6ack7Kbt+jofEBCa+aYtldH8f2xTbEzf5jw7/w4pp8LSPGz+159O8qnCy7ZYSc9Lidnp0g7Q9H5umHKOYFSzsVyYQCpoQ0aIMCgVCvmJuEq5ICTLU/jKNm39J7hHFE1YBrNoSET9uyKLAh2aAHVi2NFo7YMt0seiqycTq57+KVGb1vB5Eoy8wgh4jLO7Eh7ZvhzE0IzbyRJNHnWWCfor0aV0MUCE00O8v6Z2hmCbOyH5EpHM2wuZ/MiCAUggcAjFcKrdgpX/Tum9S1TlgAeohT04t4cn/uEhFfZXdXsguJs67up0d05qA2dAiUXUQCN8+VblDDesqxiE5EFzoXOPmeedbTWEZZOolJrfy7fQemhuyYuCGzMotinFf/dyTLYTgLnlunPR9qLjCm3dSVwmsckMiFqdCIvTjhEikYEwPf69gDi9BuYR7hKghRUBd2HeVtn/+9uN4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
